num_1 = int(input("Enter First Number: "))
num_2 = int(input("Enter Second Number: "))
print("Addition", num_1 + num_2)
print("Substraction", num_1 - num_2)
print("Multiplication", num_1 * num_2)
print("Division", num_1 / num_2)